export const THEM_PHIM = 'THEM_PHIM';
export const XOA_PHIM = 'XOA_PHIM';
export const SUA_PHIM = 'SUA_PHIM';
export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM';
export const LAY_CHI_TIET_PHIM = 'LAY_CHI_TIET_PHIM';
export const TIM_KIEM_PHIM = 'TIM_KIEM_PHIM'

export const LAY_DANH_SACH_HE_THONG_RAP ='LAY_DANH_SACH_HE_THONG_RAP';
// export const LAY_DANH_SACH_CUM_RAP ='LAY_DANH_SACH_CUM_RAP';
export const LAY_DANH_SACH_TTLC = 'LAY_DANH_SACH_TTLC';